services:

    # Print course events
    markocupic_sacpilatus.pdf_services.print_workshops_as_pdf:
        class: Markocupic\SacpilatusBundle\PdfServices\PrintWorkshopsAsPdf
        arguments:
            - "@contao.framework"

    # Download course events
    markocupic_sacpilatus.pdf_services.download_workshops_as_pdf:
        class: Markocupic\SacpilatusBundle\PdfServices\DownloadWorkshopsAsPdf
        arguments:
            - "@contao.framework"