services:

  # Contao content element Markocupic\EmployeeBundle\Controller\ContentElement\EmployeeListElementController
  Markocupic\EmployeeBundle\Controller\ContentElement\EmployeeListElementController:
    tags:
      - { name: contao.content_element, category: employee_elements, template: ce_employee_list_element, type: employee_list_element }
      - { name: container.service_subscriber }
    public: true

  # Contao content element Markocupic\EmployeeBundle\Controller\ContentElement\EmployeeSingleElementController
  Markocupic\EmployeeBundle\Controller\ContentElement\EmployeeSingleElementController:
    tags:
      - { name: contao.content_element, category: employee_elements, template: ce_employee_single_element, type: employee_single_element }
      - { name: container.service_subscriber }
    public: true