services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Markocupic\EmployeeBundle\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Model}
